openapi: 3.1.0
info:
  title: UUID Generator API
  description: API that generates random UUIDs (v4) for use in ChatGPT Actions
  version: 1.0.0
servers:
  - url: https://uuid-mcp.vercel.app

paths:
  /api/random-uuid:
    get:
      operationId: generateRandomUUID
      summary: Generate a random UUID
      description: Returns a randomly generated UUID (v4) along with the generation timestamp
      tags:
        - UUID
      responses:
        '200':
          description: Successful response with UUID and timestamp
          content:
            application/json:
              schema:
                type: object
                properties:
                  uuid:
                    type: string
                    format: uuid
                    description: A randomly generated UUID v4
                  timestamp:
                    type: string
                    format: date-time
                    description: ISO 8601 timestamp of when the UUID was generated
                required:
                  - uuid
                  - timestamp
